---
- name: Automate Ubuntu setup
  hosts: localhost

  tasks:
    # - block:
    #     - include_tasks: tasks/packages.yml
    #   become: yes
    #   become_user: root
    

    - block:
        - include_tasks: tasks/terminal.yml # This needs to be run as the target user
      become: yes
      become_user: "{{ target_user }}"
      vars:
        xdg_config_home: "/home/{{ target_user }}/.config"
        xdg_data_home: "{{ xdg_config_home }}/local/share"



  # vars:
  #     target_user: "philo"
  # tasks:
  #   - include_tasks: tasks/update.yml
  #   - include_tasks: tasks/packages.yml
  #   - include_tasks: tasks/ssh.yml
  #   - include_tasks: tasks/terminal.yml
      # vars:
      #   target_user: "{{ target_user }}"  # Pass target_user to included task
    # - include_tasks: tasks/chrome.yml
    # - include_tasks: tasks/nala.yml
    # - include_tasks: tasks/remove_snap.yml
    # - include_tasks: tasks/nerd_fonts.yml
    # - include_tasks: tasks/vscode.yml
    # - include_tasks: tasks/zsh.yml
    # - include_tasks: tasks/zsh_extensions.yml
    # - include_tasks: tasks/ohmyzsh_themes.yml
    # - include_tasks: tasks/apache.yml
    # - include_tasks: tasks/anaconda.yml
