---
# *** ___ Anaconda ___ ***
# This setup of Anaconda is based on the instructions from the official website.

# Step 1: Dependencies
- name: Install dependencies
  apt:
    name:
      - libgl1-mesa-glx
      - libegl1-mesa
      - libxrandr2
      - libxss1
      - libxcursor1
      - libxcomposite1
      - libasound2
      - libxi6
      - libxtst6
    state: present

# Step 2: Look for the latest linux version of anaconda x86_64 in the https://repo.anaconda.com/archive
- name: Find the lastest anaconda version
  shell: curl -s https://repo.anaconda.com/archive/ | grep -oP 'Anaconda3-\d+\.\d+-\d-Linux-x86_64.sh' | sort -V | tail -n 1
  register: latest_anaconda_version

# Step 3: Download
- name: Download the latest anaconda version
  get_url:
    url: "https://repo.anaconda.com/archive/{{ latest_anaconda_version.stdout }}"
    dest: "/tmp/{{ latest_anaconda_version.stdout }}"
    mode: 0755

# Step 4: Install
- name: Install anaconda
  shell: "yes | /tmp/{{ latest_anaconda_version.stdout }} -b -p {{ ansible_env.HOME }}/anaconda3"
  args:
    executable: /bin/bash

# Step 5: Initialize anaconda
# Step 5a: for bash
- name: Initialize anaconda for bash
  shell: "{{ ansible_env.HOME }}/anaconda3/bin/conda init bash"
  args:
    executable: /bin/bash

# Step 5b: for zsh
- name: Initialize anaconda for zsh
  shell: "{{ ansible_env.HOME }}/anaconda3/bin/conda init zsh"
  args:
    executable: /bin/zsh

# Step 6: Configuration
# Step 6a: Disable automatic activation of base environment
- name: Disable automatic activation of base environment
  shell: "{{ ansible_env.HOME }}/anaconda3/bin/conda config --set auto_activate_base false"
  args:
    executable: /bin/bash

# Step 6b: Disable prompt modification
- name: Disable prompt modification
  shell: "{{ ansible_env.HOME }}/anaconda3/bin/conda config --set changeps1 false"
  args:
    executable: /bin/bash


# TODO: Eventually, treat .bashrc like i do with .zshrc
# Step 7: Source the .bashrc file
- name: Source the .bashrc file
  shell: source {{ ansible_env.HOME }}/.bashrc
  args:
    executable: /bin/bash

# Step 8: Source the .zshrc file
- name: Source the .zshrc file
  shell: source "{{ xdg_config_home }}/zsh/.zshrc"
  args:
    executable: /bin/zsh


