---
- name: Initialize variables for current year, month, and retries
  set_fact:
    current_year: "{{ lookup('pipe', 'date +%Y') }}"
    current_month: "{{ lookup('pipe', 'date +%m') | int }}"
    retries_left: 100  # Maximum retries (8 years)
    anaconda_check_status: 404  # Initialize to invalid status

- name: Loop to find a valid Anaconda version
  while: retries_left > 0 and anaconda_check_status != 200
  block:
    - name: Format Anaconda version string
      set_fact:
        anaconda_version: "{{ '%04d.%02d' | format(current_year|int, current_month|int) }}"
        anaconda_file: "Anaconda3-{{ anaconda_version }}-Linux-x86_64.sh"

    - name: Check if Anaconda file exists
      uri:
        url: "https://repo.anaconda.com/archive/{{ anaconda_file }}"
        method: HEAD
      register: anaconda_check
      failed_when: false

    - name: Update anaconda check status
      set_fact:
        anaconda_check_status: "{{ anaconda_check.status }}"

    - name: Decrement month and retry if file not found
      set_fact:
        current_month: "{{ (current_month - 1) if current_month > 1 else 12 }}"
        current_year: "{{ current_year|int - 1 if current_month == 12 else current_year }}"
        retries_left: "{{ retries_left - 1 }}"
      when: anaconda_check_status != 200

- name: Fail if no valid version is found
  fail:
    msg: "Could not find a valid Anaconda version after 100 retries."
  when: retries_left == 0 and anaconda_check_status != 200

- name: Download the Anaconda installer
  get_url:
    url: "https://repo.anaconda.com/archive/{{ anaconda_file }}"
    dest: "/tmp/{{ anaconda_file }}"
    mode: '0755'

- name: Run the Anaconda installer
  shell: "bash /tmp/{{ anaconda_file }} -b"
  args:
    executable: /bin/bash

- name: Update conda packages
  shell: "echo 'y' | /home/{{ target_user }}/anaconda3/bin/conda update --all"
  args:
    executable: /bin/bash

- name: Clean up installation file
  file:
    path: "/tmp/{{ anaconda_file }}"
    state: absent
