---
- name: Download Anaconda installer
  get_url:
    url: https://repo.anaconda.com/archive/Anaconda3-2023.09-Linux-x86_64.sh
    dest: /tmp/Anaconda3-2023.09-Linux-x86_64.sh

- name: Install Anaconda
  shell: |
    bash /tmp/Anaconda3-2023.09-Linux-x86_64.sh -b -p ~/anaconda3
  args:
    executable: /bin/bash

- name: Set up Anaconda in .bashrc
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH="~/anaconda3/bin:$PATH"'
    insertafter: EOF
