---
- name: Install necessary packages
  apt:
    name:
      - curl
      - wget
      - git
      - build-essential
      - vim
      - stow
      - nano
      - htop
      - tmux

    state: present

# Print a message to the console
- debug:
    msg: "Installation of necessary packages complete."
