---
- name: Update
  apt:
    update_cache: yes

- name: Upgrade
  apt:
    upgrade: dist
    force_apt_get: yes

- name: Install necessary packages
  apt:
    name:
      - curl
      - wget
      - git
      - build-essential
      - vim
      - stow
      - nano
      - htop
      - gh
      - zsh
      - tmux
      
    state: present


# Install starship prompt 
- name: Install starship prompt
  shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
