# Install and Enable SSH
---
- name: Install SSH
  apt:
    name: openssh-server
    state: present

- name: Start SSH
  service:
    name: ssh
    state: started
    enabled: yes

# SSHD
- name: Install SSHD
  apt:
    name: openssh-client
    state: present

- name: Start SSHD
  service:
    name: sshd
    state: started
    enabled: yes