---
# *** ___ Terminal Tools ___ ***
# 1. Start with the dotfiles, since that defines where XDG_CONFIG_HOME is and by proxy where the rest of the tools will be installed.
#     1a. Check if the dotfiles repo is already cloned
#     1b. If not, clone the repo
#     1c. If it is, pull the latest changes
#     1d. Use stow to install the dotfiles


# *** ___ Dotfiles ___ ***
# Check if repo is already cloned
- name: Check if dotfiles directory exists
  stat:
    path: "/home/{{ target_user }}/dotfiles"
  register: dotfiles_directory

# If not cloned, clone the repo

#! Cloning the first ever repo using ssh will require the user to accept the host key,
# ! This is not tested
# TODO Test this
- name: Ensure SSH known_hosts directory exists
  file:
    path: "/home/{{ target_user }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ target_user }}"
    group: "{{ target_user }}"

- name: Accept GitHub host key
  shell: ssh-keyscan github.com >> /home/{{ target_user }}/.ssh/known_hosts
  args:
    creates: "/home/{{ target_user }}/.ssh/known_hosts"

- name: Clone dotfiles 
  git:
    repo: git@github.com:Phelz/dotfiles.git
    dest: "/home/{{ target_user }}/dotfiles"
  when: not dotfiles_directory.stat.exists

# Otherwise, pull the latest changes
- name: Pull dotfiles
  git:
    repo: git@github.com:Phelz/dotfiles.git
    dest: "/home/{{ target_user }}/dotfiles"
    update: yes
  when: dotfiles_directory.stat.exists

# Finally, use stow to install the dotfiles
- name: Install dotfiles
  shell: cd "/home/{{ target_user }}/dotfiles" && stow .


# *** ___ zoxide ___ ***
# Install zoxide, doesn't matter if it's already installed
- name: Install zoxide
  shell: curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh

# Install fzf
# First check it's not already installed, and if so, clone it
- name: Check if fzf is already installed
  stat:
    path: "/home/{{ target_user }}/.fzf"
  register: fzf_installed

- name: Install fzf
  shell: git clone --depth 1 https://github.com/junegunn/fzf.git /home/{{ target_user }}/.fzf && /home/{{ target_user }}/.fzf/install
  when: not fzf_installed.stat.exists

# *** ___ Tmux ___ ***
# Even if tpm is already installed, we need it under /home/user/.config/tmux/plugins/tpm, so only check if its installed there
# Check
- name: Check if tpm is already installed
  stat: 
    path: "{{ xdg_config_home }}/tmux/plugins/tpm"
  register: tpm_installed

# Install tpm
- name: Install tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ xdg_config_home }}/tmux/plugins/tpm"
  when: not tpm_installed.stat.exists


# *** ___ Starship ___ ***
- name: Install starship prompt
  shell: curl -sS https://starship.rs/install.sh | sh -s -- -y




# *** ___ Zap ___ ***
# Install zap after the dotfiles have been copied
- name: Install zap plugin manager
  shell: zsh <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh) --branch release-v1 -k
  args:
    executable: /bin/zsh

# Remove the default .zshrc file that comes in the home directory
- name: Remove default .zshrc file
  file:
    path: "/home/{{ target_user }}/.zshrc"
    state: absent