---
- name: Update
  apt:
    update_cache: yes

- name: Upgrade
  apt:
    upgrade: dist
    force_apt_get: yes

- name: Install necessary packages
  apt:
    name:
      - curl
      - wget
      - git
      - build-essential
      - vim
      - stow
      - nano
      - htop
      - gh
      - zsh
      - tmux
    state: present

