---
- name: Add Microsoft GPG key
  shell: |
    wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /usr/share/keyrings/packages.microsoft.gpg
  args:
    executable: /bin/bash

- name: Add VSCode repository
  shell: |
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list
  args:
    executable: /bin/bash

- name: Install VSCode
  apt:
    name: code
    state: present
