---
- name: Install Zsh syntax highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: Install Zsh autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: Install you-should-use plugin
  git:
    repo: https://github.com/MichaelAquilina/zsh-you-should-use.git
    dest: ~/.oh-my-zsh/custom/plugins/you-should-use

- name: Add plugins to .zshrc
  lineinfile:
    path: ~/.zshrc
    regexp: '^plugins=.*'
    line: 'plugins=(git zsh-syntax-highlighting zsh-autosuggestions you-should-use)'
